// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cgIiOasxRR8NlzpSXQWLOcpeXZjfaxk',
    appId: '1:340975478903:web:5386ca95777b8d5b0d7e72',
    messagingSenderId: '340975478903',
    projectId: 'flutterexample-1',
    authDomain: 'flutterexample-1.firebaseapp.com',
    storageBucket: 'flutterexample-1.appspot.com',
    measurementId: 'G-EEJQJTY327',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXvpfJ9PMaUVEygpSqeAAvuVAB7UIiYAQ',
    appId: '1:340975478903:android:78e5af11be9bb3390d7e72',
    messagingSenderId: '340975478903',
    projectId: 'flutterexample-1',
    storageBucket: 'flutterexample-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt1iuwKUUXR_x3Zhg1v3a2AU2D48gy-d8',
    appId: '1:340975478903:ios:fabcca044c2303170d7e72',
    messagingSenderId: '340975478903',
    projectId: 'flutterexample-1',
    storageBucket: 'flutterexample-1.appspot.com',
    iosBundleId: 'com.example.firebaselesson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt1iuwKUUXR_x3Zhg1v3a2AU2D48gy-d8',
    appId: '1:340975478903:ios:134303c661845bdb0d7e72',
    messagingSenderId: '340975478903',
    projectId: 'flutterexample-1',
    storageBucket: 'flutterexample-1.appspot.com',
    iosBundleId: 'com.example.firebaselesson.RunnerTests',
  );
}
